import type { CspDirectives } from 'csp-typed-directives';

export const cspConfig = {
	'base-uri': ['self'],
	'object-src': ['self', 'blob:'],
	'script-src': [
		'self',
		'unsafe-eval',
		'unsafe-inline',
		'unsafe-hashes',
		'https://www.youtube.com',
		'https://nomercy.tv',
		'http://localhost:5503',
		'https://*.nomercy.tv',
		'https://vscode.nomercy.tv',
		'https://trailer.nomercy.tv',
		'https://*.nomercy.tv:*',
		'https://cdn.jsdelivr.net/npm/webvtt-parser@2.2.0/parser.min.js',
		'https://www.gstatic.com',
		'https://static.cloudflareinsights.com',
	],
	'style-src-attr': ['unsafe-inline'],
	'style-src': [
		'self',
		'unsafe-inline',
		'unsafe-eval',
		'https://cdn.nomercy.tv',
		'https://cdn-dev.nomercy.tv',
		'https://storage.nomercy.tv',
		'https://fonts.bunny.net',
	],
	'img-src': [
		'self',
		'blob:',
		'data:',
		'https://nomercy.tv',
		'https://*.nomercy.tv:*',
		'https://*.nomercy.tv',
		'https://*.spotify.com/*',
		'https://*.archive.org',
		'https://archive.org',
		'https://coverartarchive.org',
		'https://i.ytimg.com',
		'https://image.tmdb.org',
		'https://media.themoviedb.org',
		'https://lastfm.freetls.fastly.net',
		'https://images.fanart.tv',
		'https://assets.fanart.tv',
		'https://pub-a68768bb5b1045f296df9ea56bd53a7f.r2.dev',
		'wss://*.nomercy.tv:*',
	],
	'connect-src': [
		'self',
		'blob:',
		'data:',
		'https://nomercy.tv',
		'https://*.nomercy.tv:*',
		'https://*.nomercy.tv',
		'https://*.spotify.com',
		'https://themoviedb.org',
		'https://api.themoviedb.org',
		'https://www.themoviedb.org',
		'https://image.tmdb.org',
		'https://imdb.com',
		'https://www.imdb.com',
		'https://thetvdb.com',
		'https://www.thetvdb.com',
		'https://www.last.fm',
		'ws://*.nomercy.tv:*',
		'ws://192.168.2.201:*',
		'wss://*.nomercy.tv:*',
		'wss://127.0.0.1:*',
		'wss://localhost:*',
		'https://pub-a68768bb5b1045f296df9ea56bd53a7f.r2.dev',
		'https://raw.githubusercontent.com',
		'https://o4509253570592768.ingest.de.sentry.io',
	],
	'frame-src': [
		'self',
		'https://nomercy.tv',
		'https://*.nomercy.tv:*',
		'https://auth-dev.nomercy.tv',
		'https://auth-dev.nomercy.tv/*',
		'https://www.youtube.com',
	],
	'font-src': [
		'self',
		'blob:',
		'data:',
		'https://cdn.nomercy.tv',
		'https://cdn-dev.nomercy.tv',
		'https://fonts.bunny.net',
	],
	'media-src': [
		'self',
		'blob:',
		'data:',
		'https://nomercy.tv',
		'https://*.nomercy.tv',
		'https://*.nomercy.tv:*',
		'wss://*.nomercy.tv:*',
		'https://pub-a68768bb5b1045f296df9ea56bd53a7f.r2.dev',
	],
	'worker-src': ['self', 'blob:'],
} satisfies CspDirectives['CSP'];
